config/routes.rb
Heedfeed::Application.routes.draw do
  resources :feeds, except: :index do
    resources :items, except: [:index, :destroy]
    resources :notifications, only: :index
  end

  root to: 'feeds#new'
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  has_many :items, dependent: :destroy, order: 'created_at desc'
  has_many :new_items, class_name: 'Item', order: 'created_at desc', limit: 100
  has_many :notifications, class_name: 'Item',
                           conditions: ['read_at is not ?', nil],
                           order: 'read_at desc',
                           limit: 100


  before_create :set_identifier

  def to_param
    identifier
  end

  private

  def set_identifier
    begin 
      new_identifier = generate_identifier
    end while Feed.exists?(:identifier => new_identifier)

    self.identifier = new_identifier
  end

  def generate_identifier
    SecureRandom.hex(10).encode('UTF-8')
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :title, :description, :link
  belongs_to :feed
  before_save :fix_link

  def mark_read(options = {})
    unless read?
      self.referer = parse_referer(options[:from])
      self.read_at = Time.current
      save!
    end
  end

  def read?
    !!read_at
  end

  private
  def fix_link
    fixed_link = link.strip

    unless fixed_link.starts_with?('http://') || fixed_link.starts_with?('https://')
      fixed_link = "http://#{fixed_link}"
    end

    self.link = fixed_link
  end

  def parse_referer(referer = nil)
    ((referer && referer.strip == 'rss') ? 'rss' : 'web')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController

  def show
    @feed = Feed.find_by_identifier(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @feed }
      format.rss
    end
  end

  def new
    @feed = Feed.new

    respond_to do |format|
      format.html
      format.json { render json: @feed }
    end
  end

  def edit
    @feed = Feed.find_by_identifier(params[:id])
  end

  def create
    @feed = Feed.new(params[:feed])

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render json: @feed, status: :created, location: @feed }
      else
        format.html { render action: "new" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @feed = Feed.find_by_identifier(params[:id])

    respond_to do |format|
      if @feed.update_attributes(params[:feed])
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @feed = Feed.find_by_identifier(params[:id])
    @feed.destroy

    respond_to do |format|
      format.html { redirect_to feeds_url }
      format.json { head :ok }
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :find_feed

  def show
    @item = @feed.items.find(params[:id])

    respond_to do |format|
      format.html do
        @item.mark_read(:from => params[:from])
        redirect_to @item.link, :status => :found
      end
      format.json { render json: @item }
    end
  end

  def new
    @item = @feed.items.build

    respond_to do |format|
      format.html
      format.json { render json: @item }
    end
  end

  def edit
    @item = @feed.items.find(params[:id])
  end

  def create
    @item = @feed.items.build(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @feed, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @item = @feed.items.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def find_feed
    @feed = Feed.find_by_identifier(params[:feed_id])
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_filter :find_feed

  def index
    @notifications = @feed.notifications

    respond_to do |format|
      format.rss
    end
  end

  private
  def find_feed
    @feed = Feed.find_by_identifier(params[:feed_id])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def read_status(item)
    if item.read?
      "read from <strong>#{item.referer}</strong> (#{time_ago_in_words(item.read_at)} ago)".html_safe
    else
      'unread'
    end
  end

  def description_with_link(item)
    html = "<p>Link: #{link_to item.link, feed_item_url(item.feed, item, from: 'rss')}</p>"
    html << sanitize(item.description)

    html.html_safe
  end
end

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title, style: 'font-size: 64px; color: #555; width: 500px; font-family: \'Goudy Bookletter 1911\', serif;' %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, style: 'font-size: 16px; width:500px; height:40px' %>
  </div>
  <div class="actions">
    <% if f.object.new_record? %>
      <%= f.submit class: 'cta cta-green' %>
    <% else %>
      <%= f.submit %>
    <% end %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/new.html.erb
<h1>New feed</h1>

<%= render 'form' %>

app/views/feeds/show.html.erb
<%= auto_discovery_link_tag :rss, feed_url(@feed, format: :rss), title: @feed.title %>
<%= auto_discovery_link_tag :rss, feed_notifications_url(@feed, format: :rss), title: 'Notifications' %>

<p id="notice"><%= notice %></p>

<h1><%= @feed.title %></h1>

<p>
  <%= @feed.description %> (<%= link_to 'edit feed', edit_feed_path(@feed) %>)
</p>

<p>
  <%= link_to '+ Add Item', new_feed_item_path(@feed) %>
</p>

<ul>
  <% @feed.items.each do |item| %>
    <li>
      <h3><%= link_to item.title, feed_item_url(@feed, item) %> <span><%= read_status(item) %></span></h3>
      Link: <%= link_to item.link, feed_item_url(@feed, item) %>
      <p><%= sanitize(item.description) %></p>
      <p>
        <%= link_to 'Edit', edit_feed_item_path(item.feed, item) %>
      </p>
    </li>
  <% end %>
</ul>

app/views/items/_form.html.erb
<%= form_for([@item.feed, @item]) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', feed_item_path(@item.feed, @item) %> |
<%= link_to 'Back', @item.feed %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', @item.feed %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= sanitize(@item.title) %>
</p>

<p>
  <b>Link:</b>
  <%= link_to @item.link, feed_item_url(@item.feed, @item) %>
</p>

<p>
  <b>Description:</b>
  <%= sanitize(@item.description) %>
</p>


<%= link_to 'Edit', edit_feed_item_path(@item.feed, @item) %> |
<%= link_to 'Back', @item.feed %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Heedfeed</title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <h1 id="heedfeed"><%= link_to "# HeedFeed <span>feeds for friends.</span>".html_safe, root_url %></h1>
    <%= yield %>
  </body>
</html>